org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Enable Gradle Daemon
org.gradle.daemon=true
# Enable parallel build
org.gradle.parallel=true
# Enable configuration on demand
org.gradle.configureondemand=true
# Enable build cache
org.gradle.caching=true